# Generated by Django 4.0.4 on 2023-04-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_tax_lineitem_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax',
            new_name='total_tax',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='tax',
        ),
    ]
