# Generated by Django 4.0.4 on 2023-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rename_tax_invoice_total_tax_remove_lineitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
